language: node_js	

node_js:
  - "8"
  - "lts/*"
os:
  - linux
  - osx

script:
  - npm run package:$TRAVIS_OS_NAME

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
