language: node_js	

node_js:
  - "node"
  - "lts/*"
os:
  - linux
  - osx

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run package:$TRAVIS_OS_NAME

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
